sudo: required
services:
  - docker

before_install:
  - docker build -t amoatoz/docker-react -f Dockerfile.dev .

script:
  - docker run amoatoz/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "dockerlast"
  env: "Dockerlast-env"
  bucket_name: "elasticbeanstalk-us-west-1-548324525918"
  bucket_path: "dockerlast"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"