sudo: required
services:
  - docker

before_install:
  - docker build -t amoatoz/docker-react -f Dockerfile.dev .

script:
  - docker run amoatoz/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-548324525918"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: "AKIAIEA6UN42DE7PM5VQ"
  secret_access_key: 
    secure: "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"